# Adapted from https://github.com/itsmattkc/dotnet9x/blob/master/.github/workflows/ci.yml
name: Build - MSVC4 Release

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/checkout@v3
      with:
        repository: 'itsmattkc/msvc420'
        path: msvc420

    - name: Build winsock351
      shell: cmd
      run: |
        call .\msvc420\bin\VCVARS32.BAT x86
        nmake /f winsock351.mak CFG="winsock351 - Win32 Release"

    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: winsock351
        path: |
          Release/ws2_32.dll
          Release/ws2_32.lib
          Release/ws2_32.pdb
